#include "textflag.h"
#include "go_asm.h"

// LzmaDecOpt_arm64.s -- Go ARM64 assembly version of LzmaDec_DecodeReal_3()
// Generated by gen_lzmadec_arm64.py from LzmaDecOpt.S structure
// Original: Igor Pavlov, Public domain
// Configuration: PSHIFT=1 (16-bit probs), unrolled, LZMA_USE_4BYTES_FILL=1

// ============================================================
// Function entry
// ============================================================
TEXT ·lzmaDecodeReal3(SB), NOSPLIT|NOFRAME, $0-28

// Load arguments before adjusting RSP (ABI0: args on stack)
	MOVD	lzma+0(FP), R0
	MOVD	limit+8(FP), R1
	MOVD	bufLimit+16(FP), R2

// Allocate stack frame
	SUB	$128, RSP, RSP

// Save callee-saved registers
	STP	(R19, R20), (RSP)
	STP	(R21, R22), 16(RSP)
	STP	(R23, R24), 32(RSP)
	STP	(R25, R26), 48(RSP)
	MOVD	R27, 64(RSP)
	MOVD	R29, 72(RSP)

// Save PARAM_lzma
	MOVD	R0, 96(RSP)

	MOVD	R2, R16
	MOVD	R1, 80(RSP)

// Load struct fields
	LDP	cLzmaDec_dic(R0), (R24, R17)
	LDP	cLzmaDec_dicPos(R0), (R14, R15)
	MOVW	cLzmaDec_rep0(R0), R20
	MOVW	cLzmaDec_rep1(R0), R21
	MOVW	cLzmaDec_rep2(R0), R22
	MOVW	cLzmaDec_rep3(R0), R23

	MOVW	$32, R7
	MOVBU	cLzmaDec_pb(R0), R29
	MOVD	80(RSP), R1
	ADD	R24, R1, R1
	MOVD	R1, 80(RSP)
	MOVW	$0, R12
	LSLW	R29, R7, R29
	ADD	R24, R14, R14
	SUBW	R7, R29, R29

	MOVBU	cLzmaDec_lc(R0), R19
	MOVW	$512, R7
	MOVBU	cLzmaDec_lp(R0), R6
	ADDW	R19, R6, R6
	SUBW	$511, R19, R19
	LSLW	R6, R7, R7
	ADDW	R7, R19, R19

	MOVD	cLzmaDec_probs(R0), R26
	MOVW	cLzmaDec_checkDicSize(R0), R8
	MOVW	R8, 88(RSP)
	MOVW	cLzmaDec_processedPos(R0), R27
	MOVW	cLzmaDec_state(R0), R13
	MOVW	cLzmaDec_code(R0), R5
	MOVW	cLzmaDec_rng(R0), R0
	MOVW	$0, R3
	LSLW	$1, R13, R13

	ADD	$2816, R26, R25

// if (processedPos != 0 || checkDicSize != 0)
	MOVW	88(RSP), R8
	ORRW	R27, R8, R7
	CBZ	R7, init_skip_prev
	ADD	R17, R24, R7
	CMP	R24, R14
	CSEL	NE, R14, R7, R7
	MOVBU	-1(R7), R3
init_skip_prev:

	ANDW	R27<<5, R29, R1
	ADD	R13, R25, R6
	CMPW	$8, R13
	BLO	lit_end
	CMPW	$14, R13
	BLO	lit_matched_end
	B	lz_end

// ============================================================
// LITERAL
// ============================================================
lit_start:
	MOVW	$0, R13
lit_start_2:
	ADDW	R27<<8, R3, R3
	ADDW	$1, R27, R27
	SUBW	$2017, R2, R7
	LSLW	R19, R3, R3
	ADD	$1152, R25, R11
	ANDW	R19, R3, R3
	ADD	R3, R11, R11
	SUBW	R7->5, R2, R2
	ADD	R3<<1, R11, R11
	MOVH	R2, (R6)(R1)

	MOVHU	2(R11), R1
	TSTW	$0xFF000000, R0
	BNE	norm_1
	MOVBU.P	1(R15), R7
	LSLW	$8, R0, R0
	ORRW	R5<<8, R7, R5
norm_1:
	LSRW	$11, R0, R7
	SUBW	$2017, R1, R4
	MULW	R1, R7, R7
	MOVHU	4(R11), R8
	SUBSW	R7, R5, R6
	SUBW	R7, R0, R0
	CSELW	LO, R7, R0, R0
	CSELW	HS, R1, R4, R4
	MOVHU	6(R11), R7
	SUBW	R4->5, R1, R4
	CSELW	LO, R8, R7, R1
	CSELW	HS, R6, R5, R5
	MOVW	$2, R3
	MOVH	R4, 2(R11)
	ADCW	ZR, R3, R3
	ADD	$2, R11, R10
	TSTW	$0xFF000000, R0
	BNE	norm_2
	MOVBU.P	1(R15), R7
	LSLW	$8, R0, R0
	ORRW	R5<<8, R7, R5
norm_2:
	LSRW	$11, R0, R7
	ADDW	R3, R3, R3
	SUBW	$2017, R1, R4
	MULW	R1, R7, R7
	MOVHU	(R11)(R3<<1), R8
	SUBSW	R7, R5, R6
	SUBW	R7, R0, R0
	CSELW	LO, R7, R0, R0
	CSELW	HS, R1, R4, R4
	MOVHU	(R10)(R3<<1), R7
	SUBW	R4->5, R1, R4
	CSELW	LO, R8, R7, R1
	CSELW	HS, R6, R5, R5
	MOVH	R4, (R11)(R3)
	ADCW	ZR, R3, R3
	TSTW	$0xFF000000, R0
	BNE	norm_3
	MOVBU.P	1(R15), R7
	LSLW	$8, R0, R0
	ORRW	R5<<8, R7, R5
norm_3:
	LSRW	$11, R0, R7
	ADDW	R3, R3, R3
	SUBW	$2017, R1, R4
	MULW	R1, R7, R7
	MOVHU	(R11)(R3<<1), R8
	SUBSW	R7, R5, R6
	SUBW	R7, R0, R0
	CSELW	LO, R7, R0, R0
	CSELW	HS, R1, R4, R4
	MOVHU	(R10)(R3<<1), R7
	SUBW	R4->5, R1, R4
	CSELW	LO, R8, R7, R1
	CSELW	HS, R6, R5, R5
	MOVH	R4, (R11)(R3)
	ADCW	ZR, R3, R3
	TSTW	$0xFF000000, R0
	BNE	norm_4
	MOVBU.P	1(R15), R7
	LSLW	$8, R0, R0
	ORRW	R5<<8, R7, R5
norm_4:
	LSRW	$11, R0, R7
	ADDW	R3, R3, R3
	SUBW	$2017, R1, R4
	MULW	R1, R7, R7
	MOVHU	(R11)(R3<<1), R8
	SUBSW	R7, R5, R6
	SUBW	R7, R0, R0
	CSELW	LO, R7, R0, R0
	CSELW	HS, R1, R4, R4
	MOVHU	(R10)(R3<<1), R7
	SUBW	R4->5, R1, R4
	CSELW	LO, R8, R7, R1
	CSELW	HS, R6, R5, R5
	MOVH	R4, (R11)(R3)
	ADCW	ZR, R3, R3
	TSTW	$0xFF000000, R0
	BNE	norm_5
	MOVBU.P	1(R15), R7
	LSLW	$8, R0, R0
	ORRW	R5<<8, R7, R5
norm_5:
	LSRW	$11, R0, R7
	ADDW	R3, R3, R3
	SUBW	$2017, R1, R4
	MULW	R1, R7, R7
	MOVHU	(R11)(R3<<1), R8
	SUBSW	R7, R5, R6
	SUBW	R7, R0, R0
	CSELW	LO, R7, R0, R0
	CSELW	HS, R1, R4, R4
	MOVHU	(R10)(R3<<1), R7
	SUBW	R4->5, R1, R4
	CSELW	LO, R8, R7, R1
	CSELW	HS, R6, R5, R5
	MOVH	R4, (R11)(R3)
	ADCW	ZR, R3, R3
	TSTW	$0xFF000000, R0
	BNE	norm_6
	MOVBU.P	1(R15), R7
	LSLW	$8, R0, R0
	ORRW	R5<<8, R7, R5
norm_6:
	LSRW	$11, R0, R7
	ADDW	R3, R3, R3
	SUBW	$2017, R1, R4
	MULW	R1, R7, R7
	MOVHU	(R11)(R3<<1), R8
	SUBSW	R7, R5, R6
	SUBW	R7, R0, R0
	CSELW	LO, R7, R0, R0
	CSELW	HS, R1, R4, R4
	MOVHU	(R10)(R3<<1), R7
	SUBW	R4->5, R1, R4
	CSELW	LO, R8, R7, R1
	CSELW	HS, R6, R5, R5
	MOVH	R4, (R11)(R3)
	ADCW	ZR, R3, R3
	TSTW	$0xFF000000, R0
	BNE	norm_7
	MOVBU.P	1(R15), R7
	LSLW	$8, R0, R0
	ORRW	R5<<8, R7, R5
norm_7:
	LSRW	$11, R0, R7
	ADDW	R3, R3, R3
	SUBW	$2017, R1, R4
	MULW	R1, R7, R7
	MOVHU	(R11)(R3<<1), R8
	SUBSW	R7, R5, R6
	SUBW	R7, R0, R0
	CSELW	LO, R7, R0, R0
	CSELW	HS, R1, R4, R4
	MOVHU	(R10)(R3<<1), R7
	SUBW	R4->5, R1, R4
	CSELW	LO, R8, R7, R1
	CSELW	HS, R6, R5, R5
	MOVH	R4, (R11)(R3)
	ADCW	ZR, R3, R3

	TSTW	$0xFF000000, R0
	BNE	norm_8
	MOVBU.P	1(R15), R7
	LSLW	$8, R0, R0
	ORRW	R5<<8, R7, R5
norm_8:
	LSRW	$11, R0, R7
	ADDW	R3, R3, R3
	SUBW	$2017, R1, R4
	MULW	R1, R7, R7
	SUBSW	R7, R5, R6
	SUBW	R7, R0, R0
	CSELW	LO, R7, R0, R0
	CSELW	HS, R1, R4, R4
	CSELW	HS, R6, R5, R5
	SUBW	R4->5, R1, R4
	MOVH	R4, (R11)(R3)
	ADCW	ZR, R3, R3
	ANDW	R27<<5, R29, R1
	ADD	R13, R25, R6
	MOVB	R3, (R14)
	ADD	$1, R14, R14
	ANDW	$255, R3, R3

	CMP	R16, R15
	BHS	fin_OK
	MOVD	80(RSP), R7
	CMP	R7, R14
	BHS	fin_OK
lit_end:
	MOVHU	(R6)(R1), R2
	TSTW	$0xFF000000, R0
	BNE	norm_9
	MOVBU.P	1(R15), R7
	LSLW	$8, R0, R0
	ORRW	R5<<8, R7, R5
norm_9:
	MOVD	R0, R7
	LSRW	$11, R0, R0
	MULW	R2, R0, R0
	CMPW	R0, R5
	BLO	lit_start

// ============================================================
// MATCHES
// ============================================================
IsMatch_label:
	SUBW	R0, R5, R5
	SUBW	R0, R7, R0
	SUBW	R2->5, R2, R7
	MOVH	R7, (R6)(R1)
	MOVHU	544(R6), R2
	TSTW	$0xFF000000, R0
	BNE	norm_10
	MOVBU.P	1(R15), R7
	LSLW	$8, R0, R0
	ORRW	R5<<8, R7, R5
norm_10:
	MOVD	R0, R7
	LSRW	$11, R0, R0
	MULW	R2, R0, R0
	CMPW	R0, R5
	BHS	IsRep_label
	SUBW	$2017, R2, R7
	SUBW	R7->5, R2, R2
	MOVH	R2, 544(R6)

	SUB	$1024, R25, R11
	ORRW	$32, R13, R13

// ============================================================
// LEN DECODE
// ============================================================
len_decode:
	MOVW	$6, R12
	MOVHU	(R11), R2
	TSTW	$0xFF000000, R0
	BNE	norm_11
	MOVBU.P	1(R15), R7
	LSLW	$8, R0, R0
	ORRW	R5<<8, R7, R5
norm_11:
	MOVD	R0, R7
	LSRW	$11, R0, R0
	MULW	R2, R0, R0
	CMPW	R0, R5
	BLO	len_mid_0
	SUBW	R0, R5, R5
	SUBW	R0, R7, R0
	SUBW	R2->5, R2, R7
	MOVH	R7, (R11)
	ADD	$16, R11, R11
	MOVW	$-2, R12
	MOVHU	(R11), R2
	TSTW	$0xFF000000, R0
	BNE	norm_12
	MOVBU.P	1(R15), R7
	LSLW	$8, R0, R0
	ORRW	R5<<8, R7, R5
norm_12:
	MOVD	R0, R7
	LSRW	$11, R0, R0
	MULW	R2, R0, R0
	CMPW	R0, R5
	BLO	len_mid_0
	SUBW	R0, R5, R5
	SUBW	R0, R7, R0
	SUBW	R2->5, R2, R7
	MOVH	R7, (R11)
	ADD	$496, R11, R11

	MOVHU	2(R11), R1
	MOVW	$1, R3
	ADD	$2, R11, R10
len8_loop:
	TSTW	$0xFF000000, R0
	BNE	norm_13
	MOVBU.P	1(R15), R7
	LSLW	$8, R0, R0
	ORRW	R5<<8, R7, R5
norm_13:
	LSRW	$11, R0, R7
	ADDW	R3, R3, R3
	SUBW	$2017, R1, R4
	MULW	R1, R7, R7
	MOVHU	(R11)(R3<<1), R8
	SUBSW	R7, R5, R6
	SUBW	R7, R0, R0
	CSELW	LO, R7, R0, R0
	CSELW	HS, R1, R4, R4
	MOVHU	(R10)(R3<<1), R7
	SUBW	R4->5, R1, R4
	CSELW	LO, R8, R7, R1
	CSELW	HS, R6, R5, R5
	MOVH	R4, (R11)(R3)
	ADCW	ZR, R3, R3
	TBZ	$6, R3, len8_loop

	MOVW	$238, R12
	B	len_mid_2

len_mid_0:
	SUBW	$2017, R2, R7
	SUBW	R7->5, R2, R2
	MOVH	R2, (R11)
	ADD	R1, R11, R11
	MOVHU	2(R11), R1
	TSTW	$0xFF000000, R0
	BNE	norm_14
	MOVBU.P	1(R15), R7
	LSLW	$8, R0, R0
	ORRW	R5<<8, R7, R5
norm_14:
	LSRW	$11, R0, R7
	SUBW	$2017, R1, R4
	MULW	R1, R7, R7
	MOVHU	4(R11), R8
	SUBSW	R7, R5, R6
	SUBW	R7, R0, R0
	CSELW	LO, R7, R0, R0
	CSELW	HS, R1, R4, R4
	MOVHU	6(R11), R7
	SUBW	R4->5, R1, R4
	CSELW	LO, R8, R7, R1
	CSELW	HS, R6, R5, R5
	MOVW	$2, R3
	MOVH	R4, 2(R11)
	ADCW	ZR, R3, R3
	ADD	$2, R11, R10
len_mid_2:
	TSTW	$0xFF000000, R0
	BNE	norm_15
	MOVBU.P	1(R15), R7
	LSLW	$8, R0, R0
	ORRW	R5<<8, R7, R5
norm_15:
	LSRW	$11, R0, R7
	ADDW	R3, R3, R3
	SUBW	$2017, R1, R4
	MULW	R1, R7, R7
	MOVHU	(R11)(R3<<1), R8
	SUBSW	R7, R5, R6
	SUBW	R7, R0, R0
	CSELW	LO, R7, R0, R0
	CSELW	HS, R1, R4, R4
	MOVHU	(R10)(R3<<1), R7
	SUBW	R4->5, R1, R4
	CSELW	LO, R8, R7, R1
	CSELW	HS, R6, R5, R5
	MOVH	R4, (R11)(R3)
	ADCW	ZR, R3, R3
	TSTW	$0xFF000000, R0
	BNE	norm_16
	MOVBU.P	1(R15), R7
	LSLW	$8, R0, R0
	ORRW	R5<<8, R7, R5
norm_16:
	LSRW	$11, R0, R7
	ADDW	R3, R3, R3
	SUBW	$2017, R1, R4
	MULW	R1, R7, R7
	SUBSW	R7, R5, R6
	SUBW	R7, R0, R0
	CSELW	LO, R7, R0, R0
	CSELW	HS, R1, R4, R4
	CSELW	HS, R6, R5, R5
	SUBW	R4->5, R1, R4
	MOVH	R4, (R11)(R3)
	ADCW	ZR, R3, R3
	SUBW	R12, R3, R12
	TBZ	$5, R13, copy_match

// ============================================================
// DECODE DISTANCE
// ============================================================
	MOVW	$5, R7
	CMPW	$5, R12
	CSELW	LO, R12, R7, R7
	ADD	$384, R25, R11
	ADD	R7<<7, R11, R11

	MOVHU	2(R11), R1
	TSTW	$0xFF000000, R0
	BNE	norm_17
	MOVBU.P	1(R15), R7
	LSLW	$8, R0, R0
	ORRW	R5<<8, R7, R5
norm_17:
	LSRW	$11, R0, R7
	SUBW	$2017, R1, R4
	MULW	R1, R7, R7
	MOVHU	4(R11), R8
	SUBSW	R7, R5, R6
	SUBW	R7, R0, R0
	CSELW	LO, R7, R0, R0
	CSELW	HS, R1, R4, R4
	MOVHU	6(R11), R7
	SUBW	R4->5, R1, R4
	CSELW	LO, R8, R7, R1
	CSELW	HS, R6, R5, R5
	MOVW	$2, R3
	MOVH	R4, 2(R11)
	ADCW	ZR, R3, R3
	ADD	$2, R11, R10
	TSTW	$0xFF000000, R0
	BNE	norm_18
	MOVBU.P	1(R15), R7
	LSLW	$8, R0, R0
	ORRW	R5<<8, R7, R5
norm_18:
	LSRW	$11, R0, R7
	ADDW	R3, R3, R3
	SUBW	$2017, R1, R4
	MULW	R1, R7, R7
	MOVHU	(R11)(R3<<1), R8
	SUBSW	R7, R5, R6
	SUBW	R7, R0, R0
	CSELW	LO, R7, R0, R0
	CSELW	HS, R1, R4, R4
	MOVHU	(R10)(R3<<1), R7
	SUBW	R4->5, R1, R4
	CSELW	LO, R8, R7, R1
	CSELW	HS, R6, R5, R5
	MOVH	R4, (R11)(R3)
	ADCW	ZR, R3, R3
	TSTW	$0xFF000000, R0
	BNE	norm_19
	MOVBU.P	1(R15), R7
	LSLW	$8, R0, R0
	ORRW	R5<<8, R7, R5
norm_19:
	LSRW	$11, R0, R7
	ADDW	R3, R3, R3
	SUBW	$2017, R1, R4
	MULW	R1, R7, R7
	MOVHU	(R11)(R3<<1), R8
	SUBSW	R7, R5, R6
	SUBW	R7, R0, R0
	CSELW	LO, R7, R0, R0
	CSELW	HS, R1, R4, R4
	MOVHU	(R10)(R3<<1), R7
	SUBW	R4->5, R1, R4
	CSELW	LO, R8, R7, R1
	CSELW	HS, R6, R5, R5
	MOVH	R4, (R11)(R3)
	ADCW	ZR, R3, R3
	TSTW	$0xFF000000, R0
	BNE	norm_20
	MOVBU.P	1(R15), R7
	LSLW	$8, R0, R0
	ORRW	R5<<8, R7, R5
norm_20:
	LSRW	$11, R0, R7
	ADDW	R3, R3, R3
	SUBW	$2017, R1, R4
	MULW	R1, R7, R7
	MOVHU	(R11)(R3<<1), R8
	SUBSW	R7, R5, R6
	SUBW	R7, R0, R0
	CSELW	LO, R7, R0, R0
	CSELW	HS, R1, R4, R4
	MOVHU	(R10)(R3<<1), R7
	SUBW	R4->5, R1, R4
	CSELW	LO, R8, R7, R1
	CSELW	HS, R6, R5, R5
	MOVH	R4, (R11)(R3)
	ADCW	ZR, R3, R3
	TSTW	$0xFF000000, R0
	BNE	norm_21
	MOVBU.P	1(R15), R7
	LSLW	$8, R0, R0
	ORRW	R5<<8, R7, R5
norm_21:
	LSRW	$11, R0, R7
	ADDW	R3, R3, R3
	SUBW	$2017, R1, R4
	MULW	R1, R7, R7
	MOVHU	(R11)(R3<<1), R8
	SUBSW	R7, R5, R6
	SUBW	R7, R0, R0
	CSELW	LO, R7, R0, R0
	CSELW	HS, R1, R4, R4
	MOVHU	(R10)(R3<<1), R7
	SUBW	R4->5, R1, R4
	CSELW	LO, R8, R7, R1
	CSELW	HS, R6, R5, R5
	MOVH	R4, (R11)(R3)
	ADCW	ZR, R3, R3

	MOVD	R3, R10
	TSTW	$0xFF000000, R0
	BNE	norm_22
	MOVBU.P	1(R15), R7
	LSLW	$8, R0, R0
	ORRW	R5<<8, R7, R5
norm_22:
	LSRW	$11, R0, R7
	ADDW	R3, R3, R3
	SUBW	$2017, R1, R4
	MULW	R1, R7, R7
	SUBSW	R7, R5, R6
	SUBW	R7, R0, R0
	CSELW	LO, R7, R0, R0
	CSELW	HS, R1, R4, R4
	CSELW	HS, R6, R5, R5
	SUBW	R4->5, R1, R4
	MOVH	R4, (R11)(R3)
	ADCW	ZR, R3, R3
	ANDW	$3, R3, R3
	CMPW	$39, R10
	BLO	short_dist

	ADD	$512, R25, R11
	SUBW	$37, R10, R10
	ORRW	$2, R3, R3

// ============================================================
// DIRECT DISTANCE
// ============================================================
	TSTW	$0xFF000000, R0
	BEQ	direct_unroll
	LSRW	$1, R0, R0
	SUBSW	R0, R5, R7
	ADDW	R3, R3, R3
	CSELW	PL, R7, R5, R5
	CSINCW	MI, R3, R3, R3
	SUBSW	$1, R10, R10
	BEQ	direct_end
	TSTW	$0xFF000000, R0
	BEQ	direct_unroll
	LSRW	$1, R0, R0
	SUBSW	R0, R5, R7
	ADDW	R3, R3, R3
	CSELW	PL, R7, R5, R5
	CSINCW	MI, R3, R3, R3
	SUBSW	$1, R10, R10
	BEQ	direct_end
	TSTW	$0xFF000000, R0
	BEQ	direct_unroll
	LSRW	$1, R0, R0
	SUBSW	R0, R5, R7
	ADDW	R3, R3, R3
	CSELW	PL, R7, R5, R5
	CSINCW	MI, R3, R3, R3
	SUBSW	$1, R10, R10
	BEQ	direct_end
	TSTW	$0xFF000000, R0
	BEQ	direct_unroll
	LSRW	$1, R0, R0
	SUBSW	R0, R5, R7
	ADDW	R3, R3, R3
	CSELW	PL, R7, R5, R5
	CSINCW	MI, R3, R3, R3
	SUBSW	$1, R10, R10
	BEQ	direct_end
	TSTW	$0xFF000000, R0
	BEQ	direct_unroll
	LSRW	$1, R0, R0
	SUBSW	R0, R5, R7
	ADDW	R3, R3, R3
	CSELW	PL, R7, R5, R5
	CSINCW	MI, R3, R3, R3
	SUBSW	$1, R10, R10
	BEQ	direct_end
	TSTW	$0xFF000000, R0
	BEQ	direct_unroll
	LSRW	$1, R0, R0
	SUBSW	R0, R5, R7
	ADDW	R3, R3, R3
	CSELW	PL, R7, R5, R5
	CSINCW	MI, R3, R3, R3
	SUBSW	$1, R10, R10
	BEQ	direct_end
	TSTW	$0xFF000000, R0
	BEQ	direct_unroll
	LSRW	$1, R0, R0
	SUBSW	R0, R5, R7
	ADDW	R3, R3, R3
	CSELW	PL, R7, R5, R5
	CSINCW	MI, R3, R3, R3
	SUBSW	$1, R10, R10
	BEQ	direct_end
	TSTW	$0xFF000000, R0
	BEQ	direct_unroll
	LSRW	$1, R0, R0
	SUBSW	R0, R5, R7
	ADDW	R3, R3, R3
	CSELW	PL, R7, R5, R5
	CSINCW	MI, R3, R3, R3
	SUBSW	$1, R10, R10
	BEQ	direct_end

direct_unroll:
	MOVBU.P	1(R15), R7
	LSLW	$8, R0, R0
	ORRW	R5<<8, R7, R5
	LSRW	$1, R0, R0
	SUBSW	R0, R5, R7
	ADDW	R3, R3, R3
	CSELW	PL, R7, R5, R5
	CSINCW	MI, R3, R3, R3
	SUBSW	$1, R10, R10
	BEQ	direct_end
	LSRW	$1, R0, R0
	SUBSW	R0, R5, R7
	ADDW	R3, R3, R3
	CSELW	PL, R7, R5, R5
	CSINCW	MI, R3, R3, R3
	SUBSW	$1, R10, R10
	BEQ	direct_end
	LSRW	$1, R0, R0
	SUBSW	R0, R5, R7
	ADDW	R3, R3, R3
	CSELW	PL, R7, R5, R5
	CSINCW	MI, R3, R3, R3
	SUBSW	$1, R10, R10
	BEQ	direct_end
	LSRW	$1, R0, R0
	SUBSW	R0, R5, R7
	ADDW	R3, R3, R3
	CSELW	PL, R7, R5, R5
	CSINCW	MI, R3, R3, R3
	SUBSW	$1, R10, R10
	BEQ	direct_end
	LSRW	$1, R0, R0
	SUBSW	R0, R5, R7
	ADDW	R3, R3, R3
	CSELW	PL, R7, R5, R5
	CSINCW	MI, R3, R3, R3
	SUBSW	$1, R10, R10
	BEQ	direct_end
	LSRW	$1, R0, R0
	SUBSW	R0, R5, R7
	ADDW	R3, R3, R3
	CSELW	PL, R7, R5, R5
	CSINCW	MI, R3, R3, R3
	SUBSW	$1, R10, R10
	BEQ	direct_end
	LSRW	$1, R0, R0
	SUBSW	R0, R5, R7
	ADDW	R3, R3, R3
	CSELW	PL, R7, R5, R5
	CSINCW	MI, R3, R3, R3
	SUBSW	$1, R10, R10
	BEQ	direct_end
	LSRW	$1, R0, R0
	SUBSW	R0, R5, R7
	ADDW	R3, R3, R3
	CSELW	PL, R7, R5, R5
	CSINCW	MI, R3, R3, R3
	SUBSW	$1, R10, R10
	BEQ	direct_end
	B	direct_unroll

direct_end:
	LSLW	$4, R3, R3
	MOVW	$2, R9
// Alignment bit 0 (distance |= 1)
	TSTW	$0xFF000000, R0
	BNE	norm_23
	MOVBU.P	1(R15), R7
	LSLW	$8, R0, R0
	ORRW	R5<<8, R7, R5
norm_23:
	MOVHU	(R11)(R9), R1
	LSRW	$11, R0, R7
	MULW	R1, R7, R7
	SUBSW	R7, R5, R6
	SUBW	R7, R0, R0
	CSELW	LO, R7, R0, R0
	CSELW	HS, R6, R5, R5
	SUBW	$2017, R1, R8
	CSELW	HS, R1, R8, R8
	SUBW	R8->5, R1, R8
	MOVH	R8, (R11)(R9)
	MOVW	$2, R8
	MOVW	$4, R4
	CSELW	HS, R4, R8, R8
	ADDW	R8, R9, R9
	ORRW	$1, R3, R8
	CSELW	HS, R8, R3, R3
// Alignment bit 1 (distance |= 2)
	TSTW	$0xFF000000, R0
	BNE	norm_24
	MOVBU.P	1(R15), R7
	LSLW	$8, R0, R0
	ORRW	R5<<8, R7, R5
norm_24:
	MOVHU	(R11)(R9), R1
	LSRW	$11, R0, R7
	MULW	R1, R7, R7
	SUBSW	R7, R5, R6
	SUBW	R7, R0, R0
	CSELW	LO, R7, R0, R0
	CSELW	HS, R6, R5, R5
	SUBW	$2017, R1, R8
	CSELW	HS, R1, R8, R8
	SUBW	R8->5, R1, R8
	MOVH	R8, (R11)(R9)
	MOVW	$4, R8
	MOVW	$8, R4
	CSELW	HS, R4, R8, R8
	ADDW	R8, R9, R9
	ORRW	$2, R3, R8
	CSELW	HS, R8, R3, R3
// Alignment bit 2 (distance |= 4)
	TSTW	$0xFF000000, R0
	BNE	norm_25
	MOVBU.P	1(R15), R7
	LSLW	$8, R0, R0
	ORRW	R5<<8, R7, R5
norm_25:
	MOVHU	(R11)(R9), R1
	LSRW	$11, R0, R7
	MULW	R1, R7, R7
	SUBSW	R7, R5, R6
	SUBW	R7, R0, R0
	CSELW	LO, R7, R0, R0
	CSELW	HS, R6, R5, R5
	SUBW	$2017, R1, R8
	CSELW	HS, R1, R8, R8
	SUBW	R8->5, R1, R8
	MOVH	R8, (R11)(R9)
	MOVW	$8, R8
	MOVW	$16, R4
	CSELW	HS, R4, R8, R8
	ADDW	R8, R9, R9
	ORRW	$4, R3, R8
	CSELW	HS, R8, R3, R3
// Alignment bit 3 (distance |= 8)
	TSTW	$0xFF000000, R0
	BNE	norm_26
	MOVBU.P	1(R15), R7
	LSLW	$8, R0, R0
	ORRW	R5<<8, R7, R5
norm_26:
	MOVHU	(R11)(R9), R1
	LSRW	$11, R0, R7
	MULW	R1, R7, R7
	SUBSW	R7, R5, R6
	SUBW	R7, R0, R0
	CSELW	LO, R7, R0, R0
	CSELW	HS, R6, R5, R5
	SUBW	$2017, R1, R8
	CSELW	HS, R1, R8, R8
	SUBW	R8->5, R1, R8
	MOVH	R8, (R11)(R9)
	ORRW	$8, R3, R8
	CSELW	HS, R8, R3, R3

decode_dist_end:
	MOVW	88(RSP), R8
	TSTW	R8, R8
	CSELW	EQ, R27, R8, R7
	CMPW	R7, R3
	BHS	end_of_payload

	MOVD	R22, R23
	MOVD	R21, R22
	MOVD	R20, R21
	ADDW	$1, R3, R20
	CMPW	$46, R13
	MOVW	$14, R13
	MOVW	$20, R7
	CSELW	HS, R7, R13, R13

// ============================================================
// COPY MATCH
// ============================================================
copy_match:
	MOVD	80(RSP), R7
	SUBS	R14, R7, R2
	BEQ	fin_OK

	CMP	R12, R2
	CSEL	HS, R12, R2, R2

	SUB	R24, R14, R7
	ADD	R2, R14, R14
	ADDW	R2, R27, R27
	SUBW	R2, R12, R12

	SUBS	R20, R7, R7
	BHS	copy_no_wrap

	CMN	R2, R7
	ADD	R17, R7, R7
	BHI	copy_match_cross

copy_no_wrap:
	ADD	R24, R7, R7

// Wide copy path: non-overlapping (rep0 >= curLen) and curLen >= 16
	CMP	R2, R20
	BLO	copy_no_wrap_byte
	CMP	$16, R2
	BLO	copy_no_wrap_byte

	SUB	R2, R14, R9
	AND	$-16, R2, R8
copy_wide_loop:
	LDP	(R7), (R4, R10)
	STP	(R4, R10), (R9)
	ADD	$16, R7, R7
	ADD	$16, R9, R9
	SUBS	$16, R8, R8
	BNE	copy_wide_loop
	AND	$15, R2, R8
	CBZ	R8, copy_wide_done
copy_wide_tail:
	MOVBU	(R7), R4
	MOVB	R4, (R9)
	ADD	$1, R7, R7
	ADD	$1, R9, R9
	SUBS	$1, R8, R8
	BNE	copy_wide_tail
copy_wide_done:
	MOVBU	-1(R9), R3
	ANDW	R27<<5, R29, R1
	ADD	R13, R25, R6
	B	lz_check_limits

copy_no_wrap_byte:
	MOVBU	(R7), R3
	ADD	R2, R7, R7
	NEG	R2, R2

copy_common:
	SUB	$1, R14, R14

	ANDW	R27<<5, R29, R1
	ADD	R13, R25, R6

	ADDS	$1, R2, R2
	BEQ	copy_end

	CMPW	$1, R20
	BEQ	copy_match_0

// 4-byte copy when rep0 >= 4 and count >= 4
	CMPW	$4, R20
	BLO	copy_byte_loop
	CMN	$4, R2
	BHI	copy_byte_loop

// Flush pending R3 byte from pipelined load, then switch to
// non-pipelined access for word-aligned copies.
	MOVB	R3, (R14)(R2)
	ADDS	$1, R2, R2
	BEQ	copy_end
	SUB	$1, R7, R7

// Byte alignment until R2 is a multiple of 4
copy_word_align:
	TSTW	$3, R2
	BEQ	copy_word_loop
	MOVBU	(R7)(R2), R3
	MOVB	R3, (R14)(R2)
	ADDS	$1, R2, R2
	BNE	copy_word_align
	MOVBU	(R7), R3
	B	copy_end

copy_word_loop:
	MOVWU	(R7)(R2), R4
	MOVW	R4, (R14)(R2)
	ADDS	$4, R2, R2
	BNE	copy_word_loop
	MOVBU	(R7), R3
	B	copy_end

copy_byte_loop:
	MOVB	R3, (R14)(R2)
	MOVBU	(R7)(R2), R3
	ADDS	$1, R2, R2
	BEQ	copy_end

	MOVB	R3, (R14)(R2)
	MOVBU	(R7)(R2), R3
	ADDS	$1, R2, R2
	BNE	copy_byte_loop

copy_end:
lz_end_match:
	MOVB	R3, (R14)
	ADD	$1, R14, R14

lz_check_limits:
	CMP	R16, R15
	BHS	fin_OK
	MOVD	80(RSP), R7
	CMP	R7, R14
	BHS	fin_OK
lz_end:
	MOVHU	(R6)(R1), R2
	TSTW	$0xFF000000, R0
	BNE	norm_27
	MOVBU.P	1(R15), R7
	LSLW	$8, R0, R0
	ORRW	R5<<8, R7, R5
norm_27:
	MOVD	R0, R7
	LSRW	$11, R0, R0
	MULW	R2, R0, R0
	CMPW	R0, R5
	BHS	IsMatch_label

// ============================================================
// LITERAL MATCHED
// ============================================================
	ADDW	R27<<8, R3, R3
	ADDW	$1, R27, R27
	SUBW	$2017, R2, R7
	LSLW	R19, R3, R3
	ADD	$1152, R25, R11
	ANDW	R19, R3, R3
	ADD	R3, R11, R11
	SUBW	R7->5, R2, R2
	ADD	R3<<1, R11, R11
	MOVH	R2, (R6)(R1)

	SUB	R24, R14, R7
	SUBS	R20, R7, R7
	BHS	litm_no_wrap
	ADD	R17, R7, R7
litm_no_wrap:
	MOVBU	(R24)(R7), R9

// state -= (state < 10) ? 3 : 6
	SUBW	$12, R13, R3
	CMPW	$20, R13
	SUBW	$6, R13, R13
	CSELW	HS, R3, R13, R13

	LSLW	$2, R9, R9
	ANDW	$512, R9, R4
	ADD	$514, R11, R2
	ADDW	R9, R9, R9
	ADD	R4, R2, R2
	EORW	$512, R4, R10
	MOVHU	(R2), R1
	TSTW	$0xFF000000, R0
	BNE	norm_28
	MOVBU.P	1(R15), R7
	LSLW	$8, R0, R0
	ORRW	R5<<8, R7, R5
norm_28:
	LSRW	$11, R0, R7
	SUBW	$2017, R1, R8
	MULW	R1, R7, R7
	SUBSW	R7, R5, R6
	SUBW	R7, R0, R0
	CSELW	HS, R4, R10, R10
	CSELW	LO, R7, R0, R0
	ANDW	R10, R9, R4
	CSELW	HS, R1, R8, R8
	CSELW	HS, R6, R5, R5
	MOVW	$2, R3
	SUBW	R8->5, R1, R8
	MOVH	R8, (R2)
	ADD	R10, R11, R2
	ADCW	ZR, R3, R3
	ADD	R4, R2, R2
	EORW	R4, R10, R10
	MOVHU	(R2)(R3<<1), R1
	TSTW	$0xFF000000, R0
	BNE	norm_29
	MOVBU.P	1(R15), R7
	LSLW	$8, R0, R0
	ORRW	R5<<8, R7, R5
norm_29:
	LSRW	$11, R0, R7
	ADDW	R9, R9, R9
	SUBW	$2017, R1, R8
	MULW	R1, R7, R7
	SUBSW	R7, R5, R6
	SUBW	R7, R0, R0
	CSELW	HS, R4, R10, R10
	CSELW	LO, R7, R0, R0
	ANDW	R10, R9, R4
	CSELW	HS, R1, R8, R8
	CSELW	HS, R6, R5, R5
	SUBW	R8->5, R1, R8
	MOVH	R8, (R2)(R3<<1)
	ADD	R10, R11, R2
	ADCW	R3, R3, R3
	ADD	R4, R2, R2
	EORW	R4, R10, R10
	MOVHU	(R2)(R3<<1), R1
	TSTW	$0xFF000000, R0
	BNE	norm_30
	MOVBU.P	1(R15), R7
	LSLW	$8, R0, R0
	ORRW	R5<<8, R7, R5
norm_30:
	LSRW	$11, R0, R7
	ADDW	R9, R9, R9
	SUBW	$2017, R1, R8
	MULW	R1, R7, R7
	SUBSW	R7, R5, R6
	SUBW	R7, R0, R0
	CSELW	HS, R4, R10, R10
	CSELW	LO, R7, R0, R0
	ANDW	R10, R9, R4
	CSELW	HS, R1, R8, R8
	CSELW	HS, R6, R5, R5
	SUBW	R8->5, R1, R8
	MOVH	R8, (R2)(R3<<1)
	ADD	R10, R11, R2
	ADCW	R3, R3, R3
	ADD	R4, R2, R2
	EORW	R4, R10, R10
	MOVHU	(R2)(R3<<1), R1
	TSTW	$0xFF000000, R0
	BNE	norm_31
	MOVBU.P	1(R15), R7
	LSLW	$8, R0, R0
	ORRW	R5<<8, R7, R5
norm_31:
	LSRW	$11, R0, R7
	ADDW	R9, R9, R9
	SUBW	$2017, R1, R8
	MULW	R1, R7, R7
	SUBSW	R7, R5, R6
	SUBW	R7, R0, R0
	CSELW	HS, R4, R10, R10
	CSELW	LO, R7, R0, R0
	ANDW	R10, R9, R4
	CSELW	HS, R1, R8, R8
	CSELW	HS, R6, R5, R5
	SUBW	R8->5, R1, R8
	MOVH	R8, (R2)(R3<<1)
	ADD	R10, R11, R2
	ADCW	R3, R3, R3
	ADD	R4, R2, R2
	EORW	R4, R10, R10
	MOVHU	(R2)(R3<<1), R1
	TSTW	$0xFF000000, R0
	BNE	norm_32
	MOVBU.P	1(R15), R7
	LSLW	$8, R0, R0
	ORRW	R5<<8, R7, R5
norm_32:
	LSRW	$11, R0, R7
	ADDW	R9, R9, R9
	SUBW	$2017, R1, R8
	MULW	R1, R7, R7
	SUBSW	R7, R5, R6
	SUBW	R7, R0, R0
	CSELW	HS, R4, R10, R10
	CSELW	LO, R7, R0, R0
	ANDW	R10, R9, R4
	CSELW	HS, R1, R8, R8
	CSELW	HS, R6, R5, R5
	SUBW	R8->5, R1, R8
	MOVH	R8, (R2)(R3<<1)
	ADD	R10, R11, R2
	ADCW	R3, R3, R3
	ADD	R4, R2, R2
	EORW	R4, R10, R10
	MOVHU	(R2)(R3<<1), R1
	TSTW	$0xFF000000, R0
	BNE	norm_33
	MOVBU.P	1(R15), R7
	LSLW	$8, R0, R0
	ORRW	R5<<8, R7, R5
norm_33:
	LSRW	$11, R0, R7
	ADDW	R9, R9, R9
	SUBW	$2017, R1, R8
	MULW	R1, R7, R7
	SUBSW	R7, R5, R6
	SUBW	R7, R0, R0
	CSELW	HS, R4, R10, R10
	CSELW	LO, R7, R0, R0
	ANDW	R10, R9, R4
	CSELW	HS, R1, R8, R8
	CSELW	HS, R6, R5, R5
	SUBW	R8->5, R1, R8
	MOVH	R8, (R2)(R3<<1)
	ADD	R10, R11, R2
	ADCW	R3, R3, R3
	ADD	R4, R2, R2
	EORW	R4, R10, R10
	MOVHU	(R2)(R3<<1), R1
	TSTW	$0xFF000000, R0
	BNE	norm_34
	MOVBU.P	1(R15), R7
	LSLW	$8, R0, R0
	ORRW	R5<<8, R7, R5
norm_34:
	LSRW	$11, R0, R7
	ADDW	R9, R9, R9
	SUBW	$2017, R1, R8
	MULW	R1, R7, R7
	SUBSW	R7, R5, R6
	SUBW	R7, R0, R0
	CSELW	HS, R4, R10, R10
	CSELW	LO, R7, R0, R0
	ANDW	R10, R9, R4
	CSELW	HS, R1, R8, R8
	CSELW	HS, R6, R5, R5
	SUBW	R8->5, R1, R8
	MOVH	R8, (R2)(R3<<1)
	ADD	R10, R11, R2
	ADCW	R3, R3, R3
	ADD	R4, R2, R2
	MOVHU	(R2)(R3<<1), R1
	TSTW	$0xFF000000, R0
	BNE	norm_35
	MOVBU.P	1(R15), R7
	LSLW	$8, R0, R0
	ORRW	R5<<8, R7, R5
norm_35:
	LSRW	$11, R0, R7
	SUBW	$2017, R1, R8
	MULW	R1, R7, R7
	SUBSW	R7, R5, R6
	SUBW	R7, R0, R0
	CSELW	LO, R7, R0, R0
	CSELW	HS, R1, R8, R8
	CSELW	HS, R6, R5, R5
	SUBW	R8->5, R1, R8
	MOVH	R8, (R2)(R3<<1)
	ADCW	R3, R3, R3

	ANDW	R27<<5, R29, R1
	ADD	R13, R25, R6
	MOVB	R3, (R14)
	ADD	$1, R14, R14
	ANDW	$255, R3, R3

	CMP	R16, R15
	BHS	fin_OK
	MOVD	80(RSP), R7
	CMP	R7, R14
	BHS	fin_OK
lit_matched_end:
	MOVHU	(R6)(R1), R2
	TSTW	$0xFF000000, R0
	BNE	norm_36
	MOVBU.P	1(R15), R7
	LSLW	$8, R0, R0
	ORRW	R5<<8, R7, R5
norm_36:
	MOVD	R0, R7
	LSRW	$11, R0, R0
	MULW	R2, R0, R0
	CMPW	R0, R5
	BHS	IsMatch_label
	SUBW	$6, R13, R13
	B	lit_start_2

// ============================================================
// REP 0 SHORT
// ============================================================
IsRep0Short_label:
	SUBW	$2017, R2, R7
	SUBW	R7->5, R2, R2
	MOVH	R2, (R6)(R1)

	SUB	R24, R14, R7
	ORRW	$2, R13, R13
	ADDW	$1, R27, R27
	ANDW	R27<<5, R29, R1
	ADD	R13, R25, R6
	SUBS	R20, R7, R7
	BHS	rep0short_no_wrap
	ADD	R17, R7, R7
rep0short_no_wrap:
	MOVBU	(R24)(R7), R3
	B	lz_end_match

// ============================================================
// REP
// ============================================================
IsRep_label:
	SUBW	R0, R5, R5
	SUBW	R0, R7, R0
	SUBW	R2->5, R2, R7
	MOVH	R7, 544(R6)

	CMPW	$14, R13
	MOVW	$16, R13
	MOVW	$22, R2
	CSELW	HS, R2, R13, R13

	SUB	$2048, R25, R11

	MOVHU	568(R6), R2
	TSTW	$0xFF000000, R0
	BNE	norm_37
	MOVBU.P	1(R15), R7
	LSLW	$8, R0, R0
	ORRW	R5<<8, R7, R5
norm_37:
	MOVD	R0, R7
	LSRW	$11, R0, R0
	MULW	R2, R0, R0
	CMPW	R0, R5
	BHS	IsRepG0_label
	SUBW	$2017, R2, R7
	SUBW	R7->5, R2, R2
	MOVH	R2, 568(R6)
	SUB	$2560, R6, R6
	MOVHU	(R6)(R1), R2
	TSTW	$0xFF000000, R0
	BNE	norm_38
	MOVBU.P	1(R15), R7
	LSLW	$8, R0, R0
	ORRW	R5<<8, R7, R5
norm_38:
	MOVD	R0, R7
	LSRW	$11, R0, R0
	MULW	R2, R0, R0
	CMPW	R0, R5
	BLO	IsRep0Short_label
	SUBW	R0, R5, R5
	SUBW	R0, R7, R0
	SUBW	R2->5, R2, R7
	MOVH	R7, (R6)(R1)
	B	len_decode

IsRepG0_label:
	SUBW	R0, R5, R5
	SUBW	R0, R7, R0
	SUBW	R2->5, R2, R7
	MOVH	R7, 568(R6)
	MOVHU	592(R6), R2
	TSTW	$0xFF000000, R0
	BNE	norm_39
	MOVBU.P	1(R15), R7
	LSLW	$8, R0, R0
	ORRW	R5<<8, R7, R5
norm_39:
	MOVD	R0, R7
	LSRW	$11, R0, R0
	MULW	R2, R0, R0
	CMPW	R0, R5
	BHS	IsRepG1_label
	SUBW	$2017, R2, R7
	SUBW	R7->5, R2, R2
	MOVH	R2, 592(R6)
	MOVD	R21, R3
	MOVD	R20, R21
	MOVD	R3, R20
	B	len_decode

IsRepG1_label:
	SUBW	R0, R5, R5
	SUBW	R0, R7, R0
	SUBW	R2->5, R2, R7
	MOVH	R7, 592(R6)
	MOVHU	616(R6), R2
	TSTW	$0xFF000000, R0
	BNE	norm_40
	MOVBU.P	1(R15), R7
	LSLW	$8, R0, R0
	ORRW	R5<<8, R7, R5
norm_40:
	MOVD	R0, R7
	LSRW	$11, R0, R0
	MULW	R2, R0, R0
	CMPW	R0, R5
	BHS	IsRepG2_label
	SUBW	$2017, R2, R7
	SUBW	R7->5, R2, R2
	MOVH	R2, 616(R6)
	MOVD	R22, R3
	MOVD	R21, R22
	MOVD	R20, R21
	MOVD	R3, R20
	B	len_decode

IsRepG2_label:
	SUBW	R0, R5, R5
	SUBW	R0, R7, R0
	SUBW	R2->5, R2, R7
	MOVH	R7, 616(R6)
	MOVD	R23, R3
	MOVD	R22, R23
	MOVD	R21, R22
	MOVD	R20, R21
	MOVD	R3, R20
	B	len_decode

// ============================================================
// SHORT DISTANCE
// ============================================================
short_dist:
	SUBSW	$33, R10, R10
	BLS	decode_dist_end
	ORRW	$2, R3, R3
	LSLW	R10, R3, R3
	ADD	R3<<1, R26, R3
	ADD	$2, R3, R3
	MOVW	$2, R9
spec_loop:
	MOVHU	(R3), R1
	MOVD	R3, R11
	ADD	R9, R3, R3
	TSTW	$0xFF000000, R0
	BNE	norm_41
	MOVBU.P	1(R15), R7
	LSLW	$8, R0, R0
	ORRW	R5<<8, R7, R5
norm_41:
	LSRW	$11, R0, R7
	ADD	R9, R3, R8
	MULW	R1, R7, R7
	SUBSW	R7, R5, R6
	SUBW	R7, R0, R0
	CSEL	HS, R8, R3, R3
	CSELW	LO, R7, R0, R0
	SUBW	$2017, R1, R7
	CSELW	HS, R6, R5, R5
	CSELW	HS, R1, R7, R7
	ADDW	R9, R9, R9
	SUBW	R7->5, R1, R7
	MOVH	R7, (R11)
	SUBSW	$1, R10, R10
	BNE	spec_loop

	ADD	R26, R9, R9
	SUB	R9, R3, R3
	LSRW	$1, R3, R3
	B	decode_dist_end

// ============================================================
// COPY MATCH 0
// ============================================================
copy_match_0:
	MOVB	R3, (R14)(R2)
	ADDS	$1, R2, R2
	BEQ	copy_end

	MOVB	R3, (R14)(R2)
	ADDS	$1, R2, R2
	BEQ	copy_end

	MOVB	R3, (R14)(R2)
	ADDS	$1, R2, R2
	BEQ	copy_end

	ORRW	R3<<8, R3, R4
	AND	$-4, R2, R2
	ORRW	R4<<16, R4, R4

copy_match_0_small:
	MOVW	R4, (R14)(R2)
	ADDS	$4, R2, R2
	BNE	copy_match_0_small
	B	copy_end

// ============================================================
// COPY MATCH CROSS
// ============================================================
copy_match_cross:
	NEG	R2, R2

copy_cross_loop:
	MOVBU	(R24)(R7), R3
	ADD	$1, R7, R7
	MOVB	R3, (R14)(R2)
	ADD	$1, R2, R2
	CMP	R17, R7
	BNE	copy_cross_loop

	MOVBU	(R24), R3
	SUB	R2, R24, R7
	B	copy_common

// ============================================================
// ERROR / END OF PAYLOAD
// ============================================================
fin_ERROR_MATCH_DIST:
	ADDW	$512, R12, R12
	MOVD	R22, R23
	MOVD	R21, R22
	MOVD	R20, R21
	MOVD	R3, R20
	CMPW	$46, R13
	MOVW	$14, R13
	MOVW	$20, R7
	CSELW	HS, R7, R13, R13
	MOVW	$1, R3
	B	fin

end_of_payload:
	ADDSW	$1, R3, R3
	BNE	fin_ERROR_MATCH_DIST

	MOVW	$274, R12
	EORW	$32, R13, R13
	B	fin_OK

fin_OK:
	MOVW	$0, R3

fin:
	TSTW	$0xFF000000, R0
	BNE	norm_42
	MOVBU.P	1(R15), R7
	LSLW	$8, R0, R0
	ORRW	R5<<8, R7, R5
norm_42:

// Store results back to struct
	MOVD	96(RSP), R7
	SUB	R24, R14, R14
	LSRW	$1, R13, R13

	STP	(R14, R15), (cLzmaDec_dicPos)(R7)
	MOVW	R0, cLzmaDec_rng(R7)
	MOVW	R5, cLzmaDec_code(R7)
	MOVW	R27, cLzmaDec_processedPos(R7)
	MOVW	R20, cLzmaDec_rep0(R7)
	MOVW	R21, cLzmaDec_rep1(R7)
	MOVW	R22, cLzmaDec_rep2(R7)
	MOVW	R23, cLzmaDec_rep3(R7)
	MOVW	R13, cLzmaDec_state(R7)
	MOVW	R12, cLzmaDec_remainLen(R7)

// Restore callee-saved registers
	LDP	(RSP), (R19, R20)
	LDP	16(RSP), (R21, R22)
	LDP	32(RSP), (R23, R24)
	LDP	48(RSP), (R25, R26)
	MOVD	64(RSP), R27
	MOVD	72(RSP), R29

	ADD	$128, RSP, RSP

	MOVW	R3, ret+24(FP)
	RET

